### ISSUE TITLE
Old hex background

### ISSUE THREAD

**Issue by EETagent** [lilbud/es-theme-minimal#1]
Hello, where to find old hex background?
Thanks, Franta Zakopal
![snimek obrazovky 2018-04-27 v 19 56 26](https://user-images.githubusercontent.com/20557318/39378280-3199a8dc-4a58-11e8-8653-e0234b77a3d7.png)

**Comment by lilbud** [comment]
https://imgur.com/C5Mm7fI

took a while to find it, but here you go :)

**Comment by EETagent** [comment]
Thank you very much.
